env: "local" # local, dev, prod
storage_path : "postgres://postgres:4650@localhost:5432/restapi_dev?sslmode=disable"
# storage_path : "root:@tcp(localhost:3306)/project_4"
# storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8083"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
